name: FactionMobs
main: com.gmail.scyntrus.fmob.FactionMobs
author: Scyntrus
version: 2.1_1.5.2R0.1
depends: [Factions]
softdepends: [Vault]
commands:
    fm:
        description: Faction mobs control
        usage: "/fm [spawn|order|color] [parameters]"
        aliases: fmob
    fmc:
        description: Spawn a mob on a specific faction. Designed to be used by command blocks
        usage: "/fmc MOBTYPE FACTIONTAG WORLDNAME X Y Z [[wander|patrol|move] X Y Z]"
permissions:
    fmob.spawn:
        description: Allows you to use /fm spawn
        default: true
    fmob.spawn.archer:
        description: Allows you to use /fm spawn archer with all mobs
        default: false
    fmob.spawn.mage:
        description: Allows you to use /fm spawn mage
        default: false
    fmob.spawn.swordsman:
        description: Allows you to use /fm spawn swordsman
        default: false
    fmob.spawn.titan:
        description: Allows you to use /fm spawn titan
        default: false
    fmob.color:
        description: Allows you to use /fm color
        default: true
    fmob.order:
        description: Allows you to use /fm order
        default: true
    fmob.order.move:
        description: Allows you to use /fm order moveToPoint
        default: true
    fmob.order.tp:
        description: Allows you to use /fm order [tpSpawn|tpHere]
        default: op
    fmob.bypass:
        description: Allows you to spawn mobs without restriction
        default: false
    fmob.fmc:
        description: Allows you to use /fmc, a command designed for command blocks
        default: false
    fmob.selectall:
        description: Allows you to use /fm selectall
        default: op
    